Fix build with OpenSSL 4.0
The build will fail with the following undeclared identifier error:

    memtier_benchmark.cpp:2133:18: error: use of undeclared identifier 'bitmask_is_contiguous'
     2133 |             if (!bitmask_is_contiguous(cfg->tls_protocols)) {
          |                  ^~~~~~~~~~~~~~~~~~~~~
    1 error generated.

We can fix this by declaring it before it is used.

(cherry picked from commit c035b33a20a9717e0b61399df10c2e95e51620ad)