Fix build with OpenSSL 4.0 (#548)
The build will fail with the following undeclared identifier error:

    memtier_benchmark.cpp:2133:18: error: use of undeclared identifier 'bitmask_is_contiguous'
     2133 |             if (!bitmask_is_contiguous(cfg->tls_protocols)) {
          |                  ^~~~~~~~~~~~~~~~~~~~~
    1 error generated.

We can fix this by declaring it before it is used.